baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Cian Deignan'
theme = "gallery"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    identifier = "Work"
    name = "Work"
    url = "/work/"
    weight = 1

  [[menu.main]]
    identifier = "About"
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    identifier = "Contact"
    name = "Contact"
    url = "/contact/"
    weight = 3

  [[menu.main]]
    identifier = "Shop"
    name = "Shop"
    url = "/shop/"
    weight = 4